#!/bin/bash
# This script is used to run the program
TIMEFORMAT=%R
CC=/mnt/c/Users/emrek/.jdks/openjdk-18/bin/java.exe
for input in AS-0 AS-1 EU-0 EU-1 TR-0 TR-1 TR-2
do
    echo "Running $input"
    $CC -cp bin/ Main false false 1 $input 0.05 # calculate the edges
    echo "edges calculated"

    echo "Task1 required" > cases/times/$input # clear the file
    { time $CC -cp bin/ Main true false 1 $input 0.05; } 2>> cases/times/$input # task 1 A*

    echo "Task2 bonus" >> cases/times/$input # clear the file
    { time $CC -cp bin/ Main true false 2 $input 0.05; } 2>> cases/times/$input # task 2 A*
    #echo "Task2 required" >> $input # clear the file
    #{ time $CC -cp bin/ Main true true 2 $input 0.05; } 2>> $input # task 2 dijkstra

    echo "Done $input"
done

for input in INTER-0 INTER-1 INTER-2
do
    echo "Running $input"
    $CC -cp bin/ Main false false 1 $input 0.03 # calculate the edges
    echo "edges calculated"

    echo "Task1 required" > cases/times/$input # clear the file
    { time $CC -cp bin/ Main true false 1 $input 0.03; } 2>> cases/times/$input # task 1 A*

    echo "Task2 bonus" >> cases/times/$input # clear the file
    { time $CC -cp bin/ Main true false 2 $input 0.03; } 2>> cases/times/$input # task 2 A*
    #echo "Task2 required" >> $input # clear the file
    #{ time $CC -cp bin/ Main true true 2 $input 0.03; } 2>> $input # task 2 dijkstra

    echo "Done $input"
done

